### ISSUE TITLE
@yuukieve I believe you've mislabeled the issue. It's an _exceptional_ error :^)

### ISSUE THREAD

**Issue by AshleyWrench** [AuroraWright/Luma3DS#1199]
_Originally posted by @Margen67 in https://github.com/AuroraWright/Luma3DS/issues/1187#issuecomment-431920391_

You, and possibly your team, are absolute garbage. No help in solving basic querys the community has. And for what? "it's exceptional, it's not our fault'. 

You're idiots. You have so little understanding of how the platform works, it's almost a joke.
F*** me, there are people here who have their systems corrupt because, yes "their stupid enough to buy second hand equipment". However, Facebook's API and Dev Team have a better response and answer then you guys. You  and your team literately act like children. 

Get a grip.

**Comment by yuukieve** [comment]
Margen67 is not part of the Luma team, they're just a user; anyone with a GitHub account can comment. 

Additionally, please read the issue template you get when submitting an issue; it explicitly states that the Luma3DS repository issue page is not a technical support forum, and provides a link to a place that *is*.
