### ISSUE TITLE
What I meant to say

### ISSUE THREAD

**Issue by MasterGamingYT** [AuroraWright/Luma3DS#1237]
I apologize for any inconvenience I said in the last issue, anyways, what I meant to say was: "Luma3DS is getter better and better with every release, and I hope we don't have to wait too long for the next one"
Theres your apology I guess?

**Comment by LPW00** [comment]
It is _the only cfw_ already?

**Comment by MasterGamingYT** [comment]
Except for Pasta CFW which I think is for emunand only, correct me if I'm wrong

**Comment by MasterGamingYT** [comment]
Also it does make it the best by default ^^

**Comment by LPW00** [comment]
@MasterGamingYT okay, it is the only one under active development. I should've specified that.

**Comment by MasterGamingYT** [comment]
Ok

**Comment by Margen67** [comment]
What is the point of this issue?

**Comment by MasterGamingYT** [comment]
Now that I think about it, I feel very guilty for posting issue #1224
