### ISSUE TITLE
version Number in the name of the zip file

### ISSUE THREAD

**Issue by noX1609** [AuroraWright/Luma3DS#339]
Hi,

at first its a very great work that you do here.
One feature would be a really great thing. When i build a nightly Version is it possible to add the build / commit number to the Filename? Because i like to have an archive on my NAS with all Versions and it would be great to have it. The change have to be in the Buildscript if i'm correct. So if you don't like to build it in could you at least give me the codeline that would do it so i can implement it in my own fork of luma3DS.

Would be very happy about that :)

**Comment by noX1609** [comment]
And would it even be possible to add the number to all the files?

**Comment by Shadow322** [comment]
Not happening

**Comment by noX1609** [comment]
Ok i've suceeded doing it myself :)
