### ISSUE TITLE
[Suggestion] 3D Splash Screen

### ISSUE THREAD

**Issue by kehkou** [AuroraWright/Luma3DS#458]
Would it be at all possible to update Luma to have the option to use a 3D image for the top splash screen? 
Or is it something that is not possible?
Thank you!

**Comment by jonirrings** [comment]
I suppose not. luma boots before the system load, and 3D is supported by the system. just guess

**Comment by kehkou** [comment]
That is exactly why I think it could not be possible, but I am also guessing.

As for the formatting, it is consistent with the formatting on other [Suggestion] "issue" topics.

**Comment by hartmannaf** [comment]
It could be possible, but someone would need to find out how to set up the screen that way.

**Comment by Kaisogen** [comment]
How about a menuhax like solution? Is there anything like system.xml on the Wii U on the 3DS we can edit?

This would drastically increase the amount of time Luma takes to boot, but, it could go like this.

>Install process or application

>Luma turns on. 

>Goes through regular boot 

>Automatically open application or process

>Display image for 5-3 seconds in 3D. Disable home button and no manual break so you can't exit early

> Go to home.

Something like this could work, assuming we have the technology to do it. I don't really know though.

**Comment by WubTheGame** [comment]
can we at least have animated boot screens?

**Comment by Kaisogen** [comment]
I believe BootCTR9 has support for this.

**Comment by WubTheGame** [comment]
i can't find a version of it for boot9strap though

**Comment by hartmannaf** [comment]
@WubTheGame They are inside of the gbatemp release thread: https://gbatemp.net/threads/release-the-bootctr9-release-thread.435347/page-3#post-7370533

**Comment by Hikari-chin** [comment]
Thanks. This will be implemented at some point in the future most likely, but it is not a high priority.

**Comment by TuxSH** [comment]
Closing to clean the issue tracker up
