### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by Reisyukaku** [AuroraWright/Luma3DS#56]
Removing the copyrights from the files was a violation of GPL. Please revert changes appropriately.

GPL, art.4(1):
"You may convey verbatim copies of the Program's source code as you
receive it, in any medium, provided that you conspicuously and
appropriately publish on each copy an appropriate copyright notice;
keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code;
keep intact all notices of the absence of any warranty; and give all
recipients a copy of this License along with the Program."

https://github.com/Reisyukaku/ReiNand/blob/master/LICENSE.txt#L195

**Comment by fox8091** [comment]
You can't slap copywright on files that aren't yours to begin with. The only one REMOTELY copywritable was types.h

**Comment by Reisyukaku** [comment]
The ones without copyright weren't mine, the rest were obviously. Also please prove they weren't mine.

**Comment by AtrusHB** [comment]
"Please prove they weren't mine."
[That'sNotHowItWorksYouLittleShit.png](http://wiki.magicalgirlnoir.com/images/7/70/That's_not_how_it_works_you_little_shit.png)

**Comment by Reisyukaku** [comment]
My point is, they were removed, and thats against the terms. Nothing more needs to said. The proof is in the commits.

**Comment by TuxSH** [comment]
Except for ```emunand.c```, all of the other files have been written or completely rewritten, some others came from other projects than ReiNAND.

```crypto.c``` originally comes from http://github.com/b1l1s/ctr .

Some other files (like ```types.h``` and ```memory.h/.c```) are simple enough that it is impossible to prove it's you're own. A lot of people could have written that code / you can find that code "anywhere".

**Comment by AtrusHB** [comment]
"The proof is in the commits."
I don't think you'd be liking your own posts if they actually proved anything.

**Comment by Reisyukaku** [comment]
@TuxSH The only things i didnt write were crypto.c, fatfs/sdmmc, and the linker and other pedantic things. And as such, i didnt put my name on it. Everything else is purely mine.

**Comment by ryanrocks462** [comment]
.

**Comment by RShadowhand** [comment]
I think you're just being an asshole for the sake of being one.

**Comment by TuxSH** [comment]
https://github.com/mid-kid/CakesForeveryWan/blob/master/source/fs.c
https://github.com/Reisyukaku/ReiNand/blob/fd2d29bb006d723b2db31b12061a3442560fe83d/source/fs.c

https://github.com/mid-kid/CakesForeveryWan/blob/557a8e8605ab3ee173af6497486e8f22c261d0e2/source/memfuncs.c
https://github.com/Reisyukaku/ReiNand/blob/fd2d29bb006d723b2db31b12061a3442560fe83d/source/memory.c

In these files you just copied @mid-kid's code (for at least some functions), just changing variable names; those files are license under the top-level LICENSE.txt. Where are your credits, @Reisyukaku ? Not only that, but this techinally makes your post a lie.

**Comment by Reisyukaku** [comment]
Nice using an example with my name not in it. As for memory one, only one worse that you could have used was types.h, lol.

**Comment by AuroraWright** [comment]
How exactly does that clause apply here?
"keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code" and you had exactly zero statements stating that the code was GPLed or was under the GPL.

**Comment by TuxSH** [comment]
@Reisyukaku http://www.gnu.org/licenses/gpl-faq.html#GPLOmitPreamble

**Comment by ryanrocks462** [comment]
tfw one of you autistic niggers deletes my comment qq

**Comment by OctopusRift** [comment]
@ryanrocks462 dude. gtfo.

**Comment by ryanrocks462** [comment]
@OctopusRift stopped being a faggot and trying to defend this clearly stolen code

**Comment by TuxSH** [comment]
No spam allowed.

**Comment by OctopusRift** [comment]
@ryanrocks462 go read a book on GPL

**Comment by Reisyukaku** [comment]
Ok this is getting carried away. I'm too old to deal with a bunch of children.

**Comment by ryanrocks462** [comment]
@OctopusRift be smart and figure out when GPL is being stated in a commit just not directly =)

**Comment by OctopusRift** [comment]
@ryanrocks462 this is closed.

**Comment by TuxSH** [comment]
@Reisyukaku "keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code;"

`c
/*
*   fc.c
*       by Reisyukaku
*   Copyright (c) 2015 All Rights Reserved
*/`

Where in earth does this notice says the code is under the GPL license, tell me?

**Comment by ryanrocks462** [comment]
@OctopusRift obviously

**Comment by astronautlevel2** [comment]
Also, putting a file in the root of the project isn't enough to signify code is under the GPL: http://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly

**Comment by ryanrocks462** [comment]
uh oh both of your autism is showing again :/

**Comment by ryanrocks462** [comment]
when fuckers can't handle the hate so they just remove your comments kek,  ¯\_(ツ)_/¯

**Comment by mid-kid** [comment]
Yay, GPL stuff. Sorry for piping in, shouldn't have highlighted me if you didn't want me to.  
I can't see where Reisyukaku's copyright is removed, except for `types.h`, but why would you enforce GPL on some type definitions that are pretty universal?  
But I guess I'm just repeating what everybody's already said. I'd honestly like @Reisyukaku clarificating a bit more instead of ragequitting like this.

**Comment by TuxSH** [comment]
You should add proper disclaimers to your (and your collaborators') files btw @mid-kid.

**Comment by Reisyukaku** [comment]
@mid-kid I'm not rage quiting, It's just not worth my time lol. I have shit to get done. 
As for your question, i wasnt too concerned about little thinks like types.h really.. basically everything else.

**Comment by mid-kid** [comment]
I indeed should, but I've always disliked having a huge comment at the top of each file. I just expect people to respect the license in either case (and add proper credit if copying it). It's not like I can prevent someone from removing the header if they wanted to (except calling them out for it).
Though you're right, I should, and I probably will in some commit soon.

**Comment by OctopusRift** [comment]
@mid-kid is a true gentleman.

**Comment by mid-kid** [comment]
@Reisyukaku:
>basically everything else.

Please point out what. I've checked some commits but didn't find anything, and I don't expect the regular passerby will go through all the commits before judging.

**Comment by Reisyukaku** [comment]
"It's not like I can prevent someone from removing the header if they wanted to (except calling them out for it)."

My thoughts exactly. But it's turned into a circus instead, lol

**Comment by TuxSH** [comment]
Still liking your own posts @Reisyukaku ?

**Comment by ryanrocks462** [comment]
still being autistic? @TuxSH =)

**Comment by astronautlevel2** [comment]
Had you even added a line in the readme signifying that the code was under the GPL license there would be a lot less room for debate here, but nowhere in your entire project is there any indication of licensing for the code, with the exclusion of license.txt. As I have already pointed out, that's not enough to signify the code is under GPL licensing.

**Comment by ryanrocks462** [comment]
i love how 
@TuxSH commented 24 minutes ago
>No spam allowed.

@TuxSH commented a minute ago
>>>>Still liking your own posts @Reisyukaku ?


k, fucking fag -.-

**Comment by ThievesNeverProsper** [comment]
thieving scumbags should respect the maker

**Comment by TuxSH** [comment]
As @astronautlevel2 said, you could at least add one line saying it's under the GPL.

**Comment by mid-kid** [comment]
Okay, I understand why @Reisyukaku wanted to leave.  
Comments like
>Still liking your own posts @Reisyukaku ?

And whatever ryanrocks is posting are completely inappropiate.
Count me out as well, if we can't keep this civil.

**Comment by TuxSH** [comment]
Removed the comment.

**Comment by ThievesNeverProsper** [comment]
give the man his credits you thieving scum buckets

**Comment by AuroraWright** [comment]
@ryanrocks462 What does autism have to do with anything? What if I told you I were myself?

**Comment by Youngsie1997** [comment]
TIL that "Watching" github repos is a bad idea

**Comment by ryanrocks462** [comment]
@mid-kid trust rei loves my comments ;)
and @AuroraWright you would just prove my point =)

**Comment by ThievesNeverProsper** [comment]
give Rei him credits & stop stealing his code !!!!!!!!

**Comment by Youngsie1997** [comment]
I'm all for a pissing contest and slagging match if it actually leads some where productive but its quite clear this isn't going anywhere soon so im out lol

**Comment by ThievesNeverProsper** [comment]
GIVE REI HIS CREDITS YOU CODE STEALER

**Comment by ryanrocks462** [comment]
@TuxSH their wasn't anything even basin my last comment and your removed it, lmfao your fucking ASS-Blasted Right now

**Comment by mid-kid** [comment]
>Removed the said comment.

Remivng a comment is useless when the damage is already done. I personally hate censorship, as it only helps adding more confusion (and those damn reaction icons github added recently).
Requesting anyone with privileges to lock the thread.

**Comment by ThievesNeverProsper** [comment]
GIVE REI HIS CREDITS YOU CODE STEALER

**Comment by TuxSH** [comment]
Ok, sorry for that.
It wasn't my intention.

Anyways, this is getting toxic/spammed, so I'm locking.

**Comment by ThievesNeverProsper** [comment]
!!!!!!!!! CODE STEALING SCUM !!!!!!
