### ISSUE TITLE
Error with luma3DS, freeshop and MH4U

### ISSUE THREAD

**Issue by xGawden** [AuroraWright/Luma3DS#745]
Hi guys,

I have just found a bug when i try to view the game "MH4U" on freeshop.
Freeshop load the presentation of the game and freeze 3 seconds later.

Here the picture : http://imgur.com/a/Gns3b

I have a N3DS with B9S and luma 8.1 and otherwise, all is ok for me.

Thanks for all and good evening.

**Comment by TuxSH** [comment]
Sorry, we don't support piracy.
