### ISSUE TITLE
this many this: ban me from the issues page please

### ISSUE THREAD

**Issue by PigeonBonsai** [AuroraWright/Luma3DS#967]
mama no worry hit video on monday
okay
im using luma and okay

> dog
`thisMany(this);`

**Comment by PigeonBonsai** [comment]
**+++**

**Comment by PigeonBonsai** [comment]
_+++_

**Comment by NovaPhoenix** [comment]
Why...

**Comment by PigeonBonsai** [comment]
I dunno new vid on monday for "momma dont worry" by bhad bhabie
