### ISSUE TITLE
Luma3DS freezes on black screen with blue power button when trying to shutdown using Rosalina

### ISSUE THREAD

**Issue by sandhoners123** [AuroraWright/Luma3DS#987]
I am running Fastboot3DS as my bootloader and everything but shutting down the 3DS using Rosalina works. Also this same issue happened when I was running boot9strap 1.3. OLD 2DS

**Comment by Hikari-chin** [comment]
Can't reproduce. It takes a few seconds to shutdown while sitting on that screen, but it does work.
